name: coverage
on: push
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeLaGuardo/setup-clojure@master
        with:
          tools-deps: latest
      - uses: actions/cache@v4
        with:
          path: ~/.m2
          key: coverage-m2-${{ hashFiles('deps.edn') }}-v1
      - name: Run cloverage
        env:
            CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          make coverage
          bash <(curl -s https://codecov.io/bash)
