name: dependencies
on:
  push:
  schedule:
    - cron: '0 21 * * *'
jobs:
  antq:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: liquidz/antq-action@main
        with:
          excludes: 'lambdaisland/kaocha'
