name: Tag and Release
on: workflow_dispatch

jobs:
  tag-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '11'

      - run: java -version

      - uses: DeLaGuardo/setup-clojure@master
        with:
          cli: latest

      - uses: actions/cache@v4
        with:
          path: ~/.m2
          key: test-m2-${{ hashFiles('deps.edn') }}-v1

      - name: deploy to clojars
        id: deploy
        run: clojure -T:build deploy
        env:
          CLOJARS_PASSWORD: ${{secrets.CLOJARS_PASSWORD}}
          CLOJARS_USERNAME: ${{secrets.CLOJARS_USERNAME}}

      - uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.deploy.outputs.version }}
          skipIfReleaseExists: true
          generateReleaseNotes: true
